name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: your-gcp-project-id
  GKE_CLUSTER: your-gke-cluster-name
  GKE_ZONE: your-cluster-zone
  BACKEND_IMAGE: vaishnavyejju/personal-blog-backend
  FRONTEND_IMAGE: vaishnavyejju/personal-blog-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate with Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Backend Image
      run: |
        docker build -t $BACKEND_IMAGE:latest ./backend
        docker push $BACKEND_IMAGE:latest

    - name: Build & Push Frontend Image
      run: |
        docker build -t $FRONTEND_IMAGE:latest ./frontend
        docker push $FRONTEND_IMAGE:latest

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: Upgrade Helm chart
      run: |
        helm upgrade --install personal-blog ./personal-blog-chart --set backendImage.repository=$BACKEND_IMAGE --set frontendImage.repository=$FRONTEND_IMAGE
