name: Simple CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend image
        run: |
          docker build -t vaishnavyejju/personal-blog-frontend:latest ./frontend
          docker push vaishnavyejju/personal-blog-frontend:latest

      - name: Build and push Backend image
        run: |
          docker build -t vaishnavyejju/personal-blog-backend:latest ./backend
          docker push vaishnavyejju/personal-blog-backend:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl get nodes

      - name: Install/Upgrade Helm chart
        run: |
          helm upgrade --install personal-blog ./personal-blog-chart
