apiVersion: v1
kind: Service
metadata:
  name: {{ include "personal-blog-chart.fullname" . }}-backend
  labels:
    app: {{ include "personal-blog-chart.fullname" . }}-backend
spec:
  type: {{ .Values.backendService.type }}
  ports:
    - port: {{ .Values.backendService.port }}
      targetPort: {{ .Values.backendService.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "personal-blog-chart.fullname" . }}-backend
