apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "personal-blog-chart.fullname" . }}-frontend
  labels:
    app: {{ include "personal-blog-chart.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "personal-blog-chart.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "personal-blog-chart.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontendImage.repository }}:{{ .Values.frontendImage.tag }}"
          imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontendService.port }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
